"""test_new_migration

Revision ID: a5acc3631fcb
Revises: ed9c84f666da
Create Date: 2025-09-10 15:19:00.752677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5acc3631fcb'
down_revision: Union[str, Sequence[str], None] = 'ed9c84f666da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', models.database.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_data', models.database.base.JSON(), nullable=True),
    sa.Column('id', models.database.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_table('file_contexts',
    sa.Column('session_id', models.database.base.GUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', models.database.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_projects_github_id'), table_name='projects')
    op.drop_column('projects', 'github_id')
    op.alter_column('search_cache', 'results',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_foreign_key(None, 'session_messages', 'chat_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_messages', type_='foreignkey')
    op.alter_column('search_cache', 'results',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('projects', sa.Column('github_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_projects_github_id'), 'projects', ['github_id'], unique=True)
    op.drop_table('file_contexts')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
